
language: cpp

matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
        - os: osx
          osx_image: xcode10

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: "ppa:beineri/opt-qt58-trusty"
      - sourceline: "ppa:corentinjabot/cmake-backport" #cmake 3.7.2
      # for cmake 3.12 use ppa:dluxen/cmake-backports
      - sourceline: "ppa:nschloe/eigen-backports" #eigen 3.3.2
    packages:
      - gcc-5
      - g++-5
      - libglu1-mesa-dev
      - qt58base
      - cmake
      - libeigen3-dev
      - libtinyxml2-dev/trusty-backports
  homebrew:
    packages:
      - qt5
      - eigen
      - tinyxml2

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      source /opt/qt58/bin/qt58-env.sh ;
    fi

branches:
  only:
    - develop

install:
  - git clone -b develop --depth=1  https://github.com/cgogn/CGoGN_2
  - cd CGoGN_2
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      cmake .. -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5 ; 
    fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  
      cmake .. -DCMAKE_PREFIX_PATH=$(brew --prefix qt) ; 
    fi
  - make -j2
  - sudo make install
  - cd ../..

script:
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      cmake .. 
        -DCMAKE_CXX_COMPILER=g++-5 
		-DCMAKE_C_COMPILER=gcc-5
		-DUSE_PLUGIN_cmap2_provider:BOOL=ON
		-DUSE_PLUGIN_cmap3_provider:BOOL=ON
		-DUSE_PLUGIN_import:BOOL=ON
        -DUSE_PLUGIN_surface_differential_properties:BOOL=ON
		-DUSE_PLUGIN_surface_modelisation:BOOL=ON
        -DUSE_PLUGIN_surface_render:BOOL=ON
        -DUSE_PLUGIN_surface_render_scalar:BOOL=ON
        -DUSE_PLUGIN_surface_render_transp:BOOL=ON
		-DUSE_PLUGIN_surface_render_vector:BOOL=ON
		-DUSE_PLUGIN_surface_selection:BOOL=ON
		-DUSE_PLUGIN_volume_render:BOOL=ON ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      cmake ..
	    -DCMAKE_PREFIX_PATH=$(brew --prefix qt)
		-DUSE_PLUGIN_cmap2_provider:BOOL=ON
		-DUSE_PLUGIN_cmap3_provider:BOOL=ON
		-DUSE_PLUGIN_import:BOOL=ON
		-DUSE_PLUGIN_surface_differential_properties:BOOL=ON
		-DUSE_PLUGIN_surface_modelisation:BOOL=ON
		-DUSE_PLUGIN_surface_render:BOOL=ON
		-DUSE_PLUGIN_surface_render_scalar:BOOL=ON
		-DUSE_PLUGIN_surface_render_transp:BOOL=ON
		-DUSE_PLUGIN_surface_render_vector:BOOL=ON
		-DUSE_PLUGIN_surface_selection:BOOL=ON
		-DUSE_PLUGIN_volume_render:BOOL=ON ;
    fi
- make -j2
