#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

branches:
  only:
    - develop

skip_commits:
  message: /\[skip ci\]|\[ci skip\]|\[skip appveyor\]|\[ci appveyor\]/
  files:
    - .travis*
    - data/
    - '*.md'

clone_folder: c:\projects\myproject

# fetch repository as zip archive
shallow_clone: true 

environment:
    GENERATOR: "Visual Studio 14 Win64"
    CONFIG: Debug

build:
  parallel: true
  verbosity: minimal

build_script:
  - git clone -b develop --depth=1  https://github.com/cgogn/CGoGN_2
  - cd CGoGN_2
  - md build
  - cd build
  - cmake -Wno-dev -Wno-deprecated "-G%GENERATOR%" .. -DCMAKE_SUPPRESS_REGENERATION=1 -DQt5_DIR="C:\Qt\5.8\msvc2015_64\lib\cmake\Qt5"
  - cmake --build . --config "%CONFIG%" -- /verbosity:minimal
  - cmake --build . --config "%CONFIG%" --target INSTALL -- /verbosity:minimal
  - cd ../..
  - md build
  - cd build
  - cmake -Wno-dev -Wno-deprecated "-G%GENERATOR%" ../ -DCMAKE_SUPPRESS_REGENERATION=1 -DCMAKE_PREFIX_PATH="C:\Program Files\CGoGN"
  - cmake --build . --config "%CONFIG%" -- /verbosity:minimal
  